version: "3"
services:
  maven-build:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile-build
    image: maven-build
    container_name: maven-build
    command: mvn clean install -DskipTests
    volumes:
      - /home/jack/.m2:/root/.m2
      - /home/jack/TestSpring:/app
    healthcheck:
      test: [ "CMD-SHELL", "/app/check.sh" ]
      interval: 10s
      timeout: 10s
      retries: 10
  testspring:
    build:
      context: .
      no_cache: true
    image: testspring
    container_name: testspring
    command: java -jar TestSpring-0.0.1-SNAPSHOT.jar
    ports:
      - 8888:8888
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://192.168.10.58:8888/api/user/list" ]
      interval: 20s
      timeout: 10s
      retries: 3
    depends_on:
      maven-build:
        condition: service_healthy
  helloworld:
    image: hello-world
    container_name: helloworld
    depends_on:
      testspring:
        condition: service_healthy
